# Generated by Django 4.2.2 on 2023-06-23 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='percentage_limits_model',
            fields=[
                ('percentage_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Percentage Limits',
            },
        ),
        migrations.CreateModel(
            name='transaction_types_model',
            fields=[
                ('transaction_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type_name', models.CharField(max_length=10, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction Types',
            },
        ),
        migrations.CreateModel(
            name='wallet_model',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_wallet_balance', models.FloatField(default=0.0)),
                ('saving_wallet_balance', models.FloatField(default=0.0)),
                ('wallet_update_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Wallets',
            },
        ),
    ]
