# Generated by Django 4.2.2 on 2023-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='percentage_limits_model',
            fields=[
                ('percentage_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Percentage Limits',
            },
        ),
        migrations.CreateModel(
            name='transaction_types_model',
            fields=[
                ('transaction_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type_name', models.CharField(max_length=10, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction Types',
            },
        ),
    ]
