# Generated by Django 4.2.2 on 2023-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='frequency_model',
            fields=[
                ('frequency_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Frequency',
            },
        ),
    ]
