# Generated by Django 4.2.2 on 2023-06-23 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saving', '0002_frequency_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='savings_preference_model',
            fields=[
                ('saving_preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('preference_update_date', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saving.frequency_model')),
                ('percentage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saving.percentage_limits_model')),
                ('transaction_type_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saving.transaction_types_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saving Preferences',
            },
        ),
    ]
