# Generated by Django 4.2.2 on 2023-06-23 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saving', '0004_transactions_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions_counter_model',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_counter', models.IntegerField(default=0)),
                ('counter_update_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saving.transaction_types_model')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transactions Counter',
            },
        ),
    ]
