# Generated by Django 4.2.2 on 2023-06-24 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0005_transactions_counter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions_model',
            name='payee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('7770ebea-a083-4222-bfd5-6ac942b68f41')),
        ),
    ]
