# Generated by Django 4.2.2 on 2023-06-24 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0006_transactions_model_payee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='payee',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('b7a14a9a-6db6-4aaf-b97a-5dd7b07600b5')),
        ),
    ]
