# Generated by Django 4.2.2 on 2023-06-24 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saving', '0008_alter_transactions_counter_model_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_counter_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('1a8e00c9-dff6-4154-b9c7-571e3327ced2')),
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
