# Generated by Django 4.2.2 on 2023-07-04 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0009_alter_transactions_counter_model_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('d28959c3-14c6-44ea-9087-f081568dc18d')),
        ),
    ]
