# Generated by Django 4.2.2 on 2023-07-04 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0010_alter_transactions_model_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('5298a3e4-6f2e-413f-a664-0278d6a77a46')),
        ),
    ]
