# Generated by Django 4.2.2 on 2023-09-30 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0014_savings_target_model_savings_target_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings_preference_model',
            name='savings_preference_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Active', 'Active')], default='Closed', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('54a88667-8562-4991-bf7e-68d08110a3d1')),
        ),
    ]
