# Generated by Django 4.2.2 on 2023-09-30 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0015_savings_preference_model_savings_preference_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_types_model',
            name='transaction_type_name',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('7a63072e-713c-4978-93b0-68776f793502')),
        ),
    ]
