# Generated by Django 4.2.2 on 2023-09-30 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0016_alter_transaction_types_model_transaction_type_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='billers_model',
            fields=[
                ('biller_id', models.AutoField(primary_key=True, serialize=False)),
                ('biller', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Billers',
            },
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('0d68a6a2-d67d-4125-b538-548d5f5e81a2')),
        ),
    ]
