# Generated by Django 4.2.2 on 2024-04-29 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0018_alter_billers_model_biller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('4bcfbdd8-3065-4a40-af04-902c1f60ca35')),
        ),
    ]
