# Generated by Django 4.2.2 on 2024-04-29 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0019_alter_transactions_model_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('aac8f1a5-4e5a-4349-9fe7-377f4da845ff')),
        ),
    ]
