# Generated by Django 4.2.2 on 2024-04-29 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0020_alter_transactions_model_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('e73b2f3b-beac-44af-b1e5-a27e7afa9886')),
        ),
    ]
