# Generated by Django 4.2.2 on 2024-04-29 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0021_alter_transactions_model_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('529e2328-8d01-430b-aece-b10d0a560a21')),
        ),
    ]
