# Generated by Django 4.2.2 on 2024-04-29 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0022_alter_transactions_model_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('2ee571c6-ecc5-468a-b450-6de26c4ba980')),
        ),
    ]
