# Generated by Django 4.2.2 on 2024-04-29 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0023_alter_transactions_model_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('cc1b3343-fedf-4907-8ae5-55612ddaff8d')),
        ),
    ]
