# Generated by Django 4.2.2 on 2024-05-16 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0024_alter_transactions_model_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='transaction_ref',
            field=models.UUIDField(default=uuid.UUID('7f52ef66-dec8-4622-b508-ccf8870e8a8d')),
        ),
    ]
