name: Deploy-ewallet-prod
# Trigger Deploy on Push Main Branch
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY_PROD }}
          REMOTE_HOST: ${{ secrets.HOST_DNS_PROD }}
          REMOTE_USER: ${{ secrets.USERNAME_PROD }}
          TARGET: ${{ secrets.TARGET_DIR_PROD }}

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services to start
        run: sleep 20

      # - name: Run tests (if you have tests)
      #   run: docker-compose -f docker-compose.yml exec web python manage.py test

      # Add more steps here as needed for your deployment process

      - name: Stop services and clean up
        run: docker-compose -f docker-compose.yml down
