name: Deploy-ewallet-prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Prod
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST_DNS_PROD }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          script: |
            # Navigate to the project directory
            cd ~/my_app/savings_wallet

            # Ensure Docker Compose is installed
            docker-compose --version

            # Pull the latest changes from the repository
            git pull origin main

            # Stop and remove existing containers and images
            docker-compose down --rmi all

            # Build and start the containers
            docker-compose up -d

            # Optional: Run database migrations or other setup tasks
            # docker-compose exec web python manage.py migrate

            echo 'Deployment successful'
